
* Jun 19, 2013
** 12:00
*** At work
*** Updated Nadja, wrote emails about status.
** 12:21
*** High pain (7), nerve-spreading through thorax,LA and LLQ
*** 25 mg Lyrica

** 13:14
*** nerve-pain is reduced. Still pain in neck, ULQ, LLQ
*** Will wait one hour before taking anything more.

** 14:15
*** Still pain in neck, LLQ, left hip. Arms better, but still pain in forearms.
*** 50 mg Valaron

** 14:30
*** Initial alerts on Valaron. Slight cloudy feeling, some masking of pain in neck and hands. hip still painful.
*** Some relaxation of neck and thorax around vertebrae.

** 14:41
*** Light background body tingling. Pain dulled to a 4.

** 15:37
*** Heightened sensitivity in neck. Some release of muscle tension overall and neck 'popping'.

** 15:56
*** Presented @ Sales meeting. Felt coherent and clear enough to answer questions concisely and in detail.
*** Some throbbing in neck.
*** Crazy hot, causing some discomfort.

** 16:07
*** knocked over a glass (not looking at it when reaching)

** 18:53
*** Business Dinner. Mood has been good. Pain is increasing in Neck and lower back. 5 now.

** 19:15
*** Neck pain increased (5+), LLQ increased (5+)
*** Continuing to talk, no impairment (also externally verfified)
** 19:45
*** 50 mg Valaron

** 20:15
*** First alerts

** 20:30
*** Neck down to 4
*** LLQ down to 4

** 22:30
*** Very tired. Having a hard time keeping neck up, going home.

** 23:20
*** email + facebook, pain is still 3+ neck, leg, lower back
*** taking a both
*** 50 mg lyrica

* June 20, 2013
** 00:43
*** Some reduction in pain in the thorax around the spine. More released tension.
*** Noticing joint pain more. Both hands, forearms 3+
*** Neck, back discomfort great enough to interfere with sleep.
*** First Valaron has worn off.

** 01:15
*** Still noticing significant discomfort.
*** 100 mg Valaron for bedtime.

** 3:14
*** Fell Asleep

** During night
*** Somewhat deep sleep, but moved several times due to discomfort.

** 06:45
*** Woke up from Alma
*** Permeating pain in thorax. Feels like dysasphesia 7+
*** Taking 50 mg Lyrica

** 7:25
*** Pain relief washed over me like a wave. Almost euphoric in the absence of pain. 
*** Was then able to find a comfortable position and continue resting, although Alma didn't let me sleep.
*** Help with getting Alma and Liam ready.

** 8:45
*** Wanted to try and sleep, but received call from Chiro's office that I could get an appt. @ 9:30
*** With the neck and previous thorax pain and feeling of persisting pain in LLQ, LH and neck decided to go.

** 9:45-11
*** Saw Kerry, updated on status. She tested and decided to work on the supraspinal muscle on the right side.
*** Mild adjustments. Afterwords greatly reduced body pain and general body load.


** 12:00
*** Got home. Tried to talk Silke. Errupted into an argument. She's very sad about Geordi.

** 12:35
*** Taking Strassenbahn to Haar appointment
*** 50 mg Valaron

** 13:00
*** Lunch with Nitsa. Mood ok, but on the edge of frustration/losing temper.
*** Nice lunch, then hair cut.

** 16:00
*** Tired. Walking is hard. pain increasing all over body.

** 16:45
*** It's clear the Lyrica has worn off. Pain has returned and an edginess with it.
*** 100 mg Lyrica

** 17:45
*** Home. Resting, trying to get to sleep early to compensate for low sleep yesterday.
*** 100 mg Valaron

** 19:47
*** Took bath. Watched a movie. Still pain, most demanding is neck and right forearm.
*** Low-grade headache forming, feels like lack of sleep thing.
*** It's been a rough day.

** 19:59
*** 50 mg Valaron

** 20:20
*** Lost temper with Dave Wells over laptop requisition
*** Using pferde salbe for neck/forearms

** 22:17
*** Family home, helped with bed
*** Starting sleep attempt again
*** 50 mg Valaron, 100 mg Lyrica

** 22:52
*** getting drowsy

** 23:20
*** big storms, interfered with sleep process, trying again

** 00:15
*** 50 mg valaron

** 00:46
*** sleep

** 11:12
*** woke up
*** Pain about a 5, but not glarinc, feel it mostly when moving.
*** Neck stiff. Did some light stretching.
*** 100 mg lyrica.

** 11:30
*** Breakfast and email/facebook

** 12:00
*** Coffee, work

** 13:10
*** Going to do some more stretching. Taking 50 mg Valaron to keep the pain level low.
*** Only noticable pain is bump on leg and left side of neck. Otherwise, only when moving/stretching.
*** 50 mg Valaron

** 13:36
*** Noticing low-back aggravation. I think I overdid it on Wednesday with the restaurant.

** 14:47
*** Tried to do some easy stretching. On back with knees-to-chest felt low-back pain @ 6.
*** Looks like it's not ready for me to do anything with it. Need to just rest some more.
*** 50 mg Valaron
** 18:28
*** Been working. Mostly reclined to keep weight off lower back.
*** Going ok. Keeping even-temper, but feel on the edge of frustration and that I don't have any reserves for patient discussion.
*** Mental clarity is great. Did some physics that was on the edge of my experience and felt very clear.
*** Pain is coming up again.
*** 100 mg Lyrica
** 19:47
*** Productive work discussions. Able to have three work design discussions and keep clear, though asked Blake to proxy on conversation to avoid stress/frustration factor.
*** Going to Sauna
*** 100 mg Valaron
** 22:14
*** Sauna felt good. I was able to get some of the tension in my legs, hips, and lower back out.
*** Definitely felt that I'd reached the limit at the end though.
*** Overall disposition is good. Feeling positive that the rebuilding and recovery phase will move quickly.
** 23:15
*** Nerve pain coming up again.
*** 100 mg Valaron 50 mg Lyrica
** 23:46
*** Getting drowsy.
* Sat Jun 22, 2013
** 08:50
*** Groggy upon waking, somewhat stiff, but pain levels moderate (4+)
*** 100 mg Lyrica
** 10:30
*** Silke went to yoga, took kids to baumarkt.
*** Taking prophylactic Valaron
*** Valaron 50 mg
** 12:00
*** A bit tired, but making lunch then going to the garden with Liam.
** 12:30-17:30
*** Made bow & arrow with Liam, cleaned up garden, started planting.
*** Picked cherries, played with the kids.
** 18:00
*** Pretty sore. Neck and shoulders complaining most (5+). Laying down.
*** 100 mg Lyrica 100 mg Valaron
** 21:30
*** Pferde Salbe, self-massge
** 22:30
*** Pain 4+, neck, forearms very sore
*** 100 mg Valaron
** 23:45
*** Sleep
* Sun Jun 23, 2013
** 9:45
*** Awoke with stiffness and pain in neck and lower back.
*** Somewhat groggy, but less than yesterday.
*** Dehydrated.
*** 100 mg Lyrica.
** 10:41
*** Pain in neck is greatly reduced.
*** Feeling like Lyrica dosing is steady @ 100 mg 3x/day
** 10:52
*** Pain Lower Back
*** General feeling that yesterday was a bit too much, but not as bad as Wednesday.
*** 50 mg Valaron
** 15:46
*** Have been very irritable. Easily feeling overwhelmed by noise and chaos.
*** Neck Pain starting again.
*** 100 mg Lyrica
** 20:55
*** Some yoga. Got some of the neck tension out, and some cracks left/right but neck feeling weak.
*** 150 mg Valaron
** 22:04
*** Pain is pretty high. Lots of tension in neck again. Trying 75 mg of Lyrica as a test to see if more of the pain is nerve or not, and if that helps.
*** 75 mg Lyrica.
** 23:15
*** Pain is still growing 6+ and very uncomfortable even laying. Took 75 mg of Lyrica, so don't think it's dysasphesia.
*** Taking a bath to see if that helps.
* Mon Jun 24, 2013
** 00:20
*** Bath didn't help much, was neither able to relax nor ease the pain. I did notice that heat made it worse though.
*** Taking ibuprofen to see if it's inflammatory.
*** 600 mg Ibuprofen
** 00:41
*** Tears coming to my eyes.
** 00:50
*** Significant relief on the pain. Will wait a few minutes and see how it develops.
** 01:05
*** The Ibuprofen has dealt with the mystery part of the pain, not it's back down in the 3-4 range.
*** Taking Valaron to make sure I get to sleep and not start the week off on a messed up sleep schedule.
*** 150 mg Valaron
** 03:30
*** Sleep
** 08:20
*** Woken up by kids. Pain levels ok (< 3), but feels blocked.
*** Taking more to go back to sleep, and hopefully keep the pain blocked.
*** 50 mg Lyrica, 100 mg Valaron.
** 11:00
*** Woke-up. Somewhat groggy, but feel ausgeschlaffen.
*** Coffee, breakfast, work emails.
** 12:35
*** Pain in mid-back 3+, neck stiff and 2+ on stretching.
*** Inflattion pain has not come back. I'm guessing that the inflammation yesterday was related to the 3 ice-creams I had.
*** Am going to return to zero sugar and monitor pH again.
** 15:18
*** Went to Dr. Egan. Had some moderate intensity work on LRQ and neck. Feeling sensitive and can tell it'll be a 'take it easy' day.
*** Feeling background pain registering in the head/neck and a lack of mental clarity.
*** 100 mg Lyrica
** 16:30
*** Talked to Dr. Miles about dosage levels. He was good with the levels I'm at and will prescribe enough to get through July until our next visit.
*** Also talked about irritibility and low tolerence for noise and distraction. I asked about trying the SNRI component and he agreed we can try a low dose of Duloxetine.
** 17:00
*** Feeling worn out. Walked about 1.5 km and had an espresso to see if it would help with the mental fog.
*** Got nauseated and had general feeling of disease.
*** I think I'll take coffee back out as it also causes inflammation. I also have the feeling that coffee really pulls on the energy reserves, of which I have none at the moment.
** 18:00
*** Heading out to the schmelz. Pain in head/neck/shoulders is 5+
*** 50 mg Valaron
** 18:45
*** Pain down to 4+
*** 50 mg Valaron
** 19:50
*** Neck is really sore and achy now 5+. LRQ is making itself known and clearly doesn't want to have to work any more, but pain is minimal (3+) and radiating from the point where Dr. Egan worked today.
*** 100 mg Lyrica
** 20:35
*** LRQ, surprisingly, is lower and the radiating aspect is gone. Neck is still aggravated.
*** Preparing for bed.
*** 150 mg Valaron
** 21:00
*** Sesame oil self-massage.
** 22:20
*** Only moderate relief from the Valaron so far. Did get some muscle tension release enough that I was able to adjust the neck back to where it should be, several vertebrae were quite a bit out. Now the allignment feels good, but everything is tender and weak. Did some hanging on the sport ball (supported "wheel") which felt good to unload the pressure of the skull. 
*** 100 mg Valaron
** 00:04
*** 50 mg Lyrica
** 10:51
*** Woke up feeling like I was run over by a horse.
*** Stiff all over. Going to do some stretching and see how I feel after.
*** 

