
* Jun 19, 2013
** 12:00
*** At work
*** Updated Nadja, wrote emails about status.
** 12:21
*** High pain (7), nerve-spreading through thorax,LA and LLQ
*** 25 mg Lyrica

** 13:14
*** nerve-pain is reduced. Still pain in neck, ULQ, LLQ
*** Will wait one hour before taking anything more.

** 14:15
*** Still pain in neck, LLQ, left hip. Arms better, but still pain in forearms.
*** 50 mg Valaron

** 14:30
*** Initial alerts on Valaron. Slight cloudy feeling, some masking of pain in neck and hands. hip still painful.
*** Some relaxation of neck and thorax around vertebrae.

** 14:41
*** Light background body tingling. Pain dulled to a 4.

** 15:37
*** Heightened sensitivity in neck. Some release of muscle tension overall and neck 'popping'.

** 15:56
*** Presented @ Sales meeting. Felt coherent and clear enough to answer questions concisely and in detail.
*** Some throbbing in neck.
*** Crazy hot, causing some discomfort.

** 16:07
*** knocked over a glass (not looking at it when reaching)

** 18:53
*** Business Dinner. Mood has been good. Pain is increasing in Neck and lower back. 5 now.

** 19:15
*** Neck pain increased (5+), LLQ increased (5+)
*** Continuing to talk, no impairment (also externally verfified)
** 19:45
*** 50 mg Valaron

** 20:15
*** First alerts

** 20:30
*** Neck down to 4
*** LLQ down to 4

** 22:30
*** Very tired. Having a hard time keeping neck up, going home.

** 23:20
*** email + facebook, pain is still 3+ neck, leg, lower back
*** taking a both
*** 50 mg lyrica

* June 20, 2013
** 00:43
*** Some reduction in pain in the thorax around the spine. More released tension.
*** Noticing joint pain more. Both hands, forearms 3+
*** Neck, back discomfort great enough to interfere with sleep.
*** First Valaron has worn off.

** 01:15
*** Still noticing significant discomfort.
*** 100 mg Valaron for bedtime.

** 3:14
*** Fell Asleep

** During night
*** Somewhat deep sleep, but moved several times due to discomfort.

** 06:45
*** Woke up from Alma
*** Permeating pain in thorax. Feels like dysasphesia 7+
*** Taking 50 mg Lyrica

** 7:25
*** Pain relief washed over me like a wave. Almost euphoric in the absence of pain. 
*** Was then able to find a comfortable position and continue resting, although Alma didn't let me sleep.
*** Help with getting Alma and Liam ready.

** 8:45
*** Wanted to try and sleep, but received call from Chiro's office that I could get an appt. @ 9:30
*** With the neck and previous thorax pain and feeling of persisting pain in LLQ, LH and neck decided to go.

** 9:45-11
*** Saw Kerry, updated on status. She tested and decided to work on the supraspinal muscle on the right side.
*** Mild adjustments. Afterwords greatly reduced body pain and general body load.


** 12:00
*** Got home. Tried to talk Silke. Errupted into an argument. She's very sad about Geordi.

** 12:35
*** Taking Strassenbahn to Haar appointment
*** 50 mg Valaron

** 13:00
*** Lunch with Nitsa. Mood ok, but on the edge of frustration/losing temper.
*** Nice lunch, then hair cut.

** 16:00
*** Tired. Walking is hard. pain increasing all over body.

** 16:45
*** It's clear the Lyrica has worn off. Pain has returned and an edginess with it.
*** 100 mg Lyrica

** 17:45
*** Home. Resting, trying to get to sleep early to compensate for low sleep yesterday.
*** 100 mg Valaron

** 19:47
*** Took bath. Watched a movie. Still pain, most demanding is neck and right forearm.
*** Low-grade headache forming, feels like lack of sleep thing.
*** It's been a rough day.

** 19:59
*** 50 mg Valaron

** 20:20
*** Lost temper with Dave Wells over laptop requisition
*** Using pferde salbe for neck/forearms

** 22:17
*** Family home, helped with bed
*** Starting sleep attempt again
*** 50 mg Valaron, 100 mg Lyrica

** 22:52
*** getting drowsy

** 23:20
*** big storms, interfered with sleep process, trying again

** 00:15
*** 50 mg valaron

** 00:46
*** sleep

** 11:12
*** woke up
*** Pain about a 5, but not glarinc, feel it mostly when moving.
*** Neck stiff. Did some light stretching.
*** 100 mg lyrica.

** 11:30
*** Breakfast and email/facebook

** 12:00
*** Coffee, work

** 13:10
*** Going to do some more stretching. Taking 50 mg Valaron to keep the pain level low.
*** Only noticable pain is bump on leg and left side of neck. Otherwise, only when moving/stretching.
*** 50 mg Valaron

** 13:36
*** Noticing low-back aggravation. I think I overdid it on Wednesday with the restaurant.

** 14:47
*** Tried to do some easy stretching. On back with knees-to-chest felt low-back pain @ 6.
*** Looks like it's not ready for me to do anything with it. Need to just rest some more.
*** 50 mg Valaron
** 18:28
*** Been working. Mostly reclined to keep weight off lower back.
*** Going ok. Keeping even-temper, but feel on the edge of frustration and that I don't have any reserves for patient discussion.
*** Mental clarity is great. Did some physics that was on the edge of my experience and felt very clear.
*** Pain is coming up again.
*** 100 mg Lyrica
